// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.0
// source: datastore_service.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataStoreServiceClient is the client API for DataStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataStoreServiceClient interface {
	GetAreas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAreasResponse, error)
	ReadBit(ctx context.Context, in *ReadBitRequest, opts ...grpc.CallOption) (*ReadBitResponse, error)
	WriteBit(ctx context.Context, in *WriteBitRequest, opts ...grpc.CallOption) (*Empty, error)
	ReadBits(ctx context.Context, in *ReadBitsRequest, opts ...grpc.CallOption) (*ReadBitsResponse, error)
	WriteBits(ctx context.Context, in *WriteBitsRequest, opts ...grpc.CallOption) (*Empty, error)
	ReadWord(ctx context.Context, in *ReadWordRequest, opts ...grpc.CallOption) (*ReadWordResponse, error)
	WriteWord(ctx context.Context, in *WriteWordRequest, opts ...grpc.CallOption) (*Empty, error)
	ReadWords(ctx context.Context, in *ReadWordsRequest, opts ...grpc.CallOption) (*ReadWordsResponse, error)
	WriteWords(ctx context.Context, in *WriteWordsRequest, opts ...grpc.CallOption) (*Empty, error)
	Snapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnapshotResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*Empty, error)
	ClearAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// SubscribeChanges: プロトコルクライアント（Modbus クライアント等）が書き込んだ
	// 変更のみを通知する。ホストからの WriteWord/WriteWords による書き込みは通知しない（循環防止）
	SubscribeChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (DataStoreService_SubscribeChangesClient, error)
}

type dataStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataStoreServiceClient(cc grpc.ClientConnInterface) DataStoreServiceClient {
	return &dataStoreServiceClient{cc}
}

func (c *dataStoreServiceClient) GetAreas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAreasResponse, error) {
	out := new(GetAreasResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/GetAreas", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) ReadBit(ctx context.Context, in *ReadBitRequest, opts ...grpc.CallOption) (*ReadBitResponse, error) {
	out := new(ReadBitResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/ReadBit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) WriteBit(ctx context.Context, in *WriteBitRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/WriteBit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) ReadBits(ctx context.Context, in *ReadBitsRequest, opts ...grpc.CallOption) (*ReadBitsResponse, error) {
	out := new(ReadBitsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/ReadBits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) WriteBits(ctx context.Context, in *WriteBitsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/WriteBits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) ReadWord(ctx context.Context, in *ReadWordRequest, opts ...grpc.CallOption) (*ReadWordResponse, error) {
	out := new(ReadWordResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/ReadWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) WriteWord(ctx context.Context, in *WriteWordRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/WriteWord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) ReadWords(ctx context.Context, in *ReadWordsRequest, opts ...grpc.CallOption) (*ReadWordsResponse, error) {
	out := new(ReadWordsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/ReadWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) WriteWords(ctx context.Context, in *WriteWordsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/WriteWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) Snapshot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) ClearAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.DataStoreService/ClearAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreServiceClient) SubscribeChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (DataStoreService_SubscribeChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataStoreService_ServiceDesc.Streams[0], "/plugin.v1.DataStoreService/SubscribeChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataStoreServiceSubscribeChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataStoreService_SubscribeChangesClient interface {
	Recv() (*DataChange, error)
	grpc.ClientStream
}

type dataStoreServiceSubscribeChangesClient struct {
	grpc.ClientStream
}

func (x *dataStoreServiceSubscribeChangesClient) Recv() (*DataChange, error) {
	m := new(DataChange)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataStoreServiceServer is the server API for DataStoreService service.
// All implementations must embed UnimplementedDataStoreServiceServer
// for forward compatibility
type DataStoreServiceServer interface {
	GetAreas(context.Context, *Empty) (*GetAreasResponse, error)
	ReadBit(context.Context, *ReadBitRequest) (*ReadBitResponse, error)
	WriteBit(context.Context, *WriteBitRequest) (*Empty, error)
	ReadBits(context.Context, *ReadBitsRequest) (*ReadBitsResponse, error)
	WriteBits(context.Context, *WriteBitsRequest) (*Empty, error)
	ReadWord(context.Context, *ReadWordRequest) (*ReadWordResponse, error)
	WriteWord(context.Context, *WriteWordRequest) (*Empty, error)
	ReadWords(context.Context, *ReadWordsRequest) (*ReadWordsResponse, error)
	WriteWords(context.Context, *WriteWordsRequest) (*Empty, error)
	Snapshot(context.Context, *Empty) (*SnapshotResponse, error)
	Restore(context.Context, *RestoreRequest) (*Empty, error)
	ClearAll(context.Context, *Empty) (*Empty, error)
	// SubscribeChanges: プロトコルクライアント（Modbus クライアント等）が書き込んだ
	// 変更のみを通知する。ホストからの WriteWord/WriteWords による書き込みは通知しない（循環防止）
	SubscribeChanges(*Empty, DataStoreService_SubscribeChangesServer) error
	mustEmbedUnimplementedDataStoreServiceServer()
}

// UnimplementedDataStoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataStoreServiceServer struct {
}

func (UnimplementedDataStoreServiceServer) GetAreas(context.Context, *Empty) (*GetAreasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAreas not implemented")
}
func (UnimplementedDataStoreServiceServer) ReadBit(context.Context, *ReadBitRequest) (*ReadBitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBit not implemented")
}
func (UnimplementedDataStoreServiceServer) WriteBit(context.Context, *WriteBitRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBit not implemented")
}
func (UnimplementedDataStoreServiceServer) ReadBits(context.Context, *ReadBitsRequest) (*ReadBitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBits not implemented")
}
func (UnimplementedDataStoreServiceServer) WriteBits(context.Context, *WriteBitsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteBits not implemented")
}
func (UnimplementedDataStoreServiceServer) ReadWord(context.Context, *ReadWordRequest) (*ReadWordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWord not implemented")
}
func (UnimplementedDataStoreServiceServer) WriteWord(context.Context, *WriteWordRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteWord not implemented")
}
func (UnimplementedDataStoreServiceServer) ReadWords(context.Context, *ReadWordsRequest) (*ReadWordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadWords not implemented")
}
func (UnimplementedDataStoreServiceServer) WriteWords(context.Context, *WriteWordsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteWords not implemented")
}
func (UnimplementedDataStoreServiceServer) Snapshot(context.Context, *Empty) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedDataStoreServiceServer) Restore(context.Context, *RestoreRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedDataStoreServiceServer) ClearAll(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAll not implemented")
}
func (UnimplementedDataStoreServiceServer) SubscribeChanges(*Empty, DataStoreService_SubscribeChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeChanges not implemented")
}
func (UnimplementedDataStoreServiceServer) mustEmbedUnimplementedDataStoreServiceServer() {}

// UnsafeDataStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataStoreServiceServer will
// result in compilation errors.
type UnsafeDataStoreServiceServer interface {
	mustEmbedUnimplementedDataStoreServiceServer()
}

func RegisterDataStoreServiceServer(s grpc.ServiceRegistrar, srv DataStoreServiceServer) {
	s.RegisterService(&DataStoreService_ServiceDesc, srv)
}

func _DataStoreService_GetAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).GetAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/GetAreas",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).GetAreas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_ReadBit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).ReadBit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/ReadBit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).ReadBit(ctx, req.(*ReadBitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_WriteBit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).WriteBit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/WriteBit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).WriteBit(ctx, req.(*WriteBitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_ReadBits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).ReadBits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/ReadBits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).ReadBits(ctx, req.(*ReadBitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_WriteBits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteBitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).WriteBits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/WriteBits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).WriteBits(ctx, req.(*WriteBitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_ReadWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).ReadWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/ReadWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).ReadWord(ctx, req.(*ReadWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_WriteWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteWordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).WriteWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/WriteWord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).WriteWord(ctx, req.(*WriteWordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_ReadWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).ReadWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/ReadWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).ReadWords(ctx, req.(*ReadWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_WriteWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).WriteWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/WriteWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).WriteWords(ctx, req.(*WriteWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/Snapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).Snapshot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_ClearAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServiceServer).ClearAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.DataStoreService/ClearAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServiceServer).ClearAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStoreService_SubscribeChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataStoreServiceServer).SubscribeChanges(m, &dataStoreServiceSubscribeChangesServer{stream})
}

type DataStoreService_SubscribeChangesServer interface {
	Send(*DataChange) error
	grpc.ServerStream
}

type dataStoreServiceSubscribeChangesServer struct {
	grpc.ServerStream
}

func (x *dataStoreServiceSubscribeChangesServer) Send(m *DataChange) error {
	return x.ServerStream.SendMsg(m)
}

// DataStoreService_ServiceDesc is the grpc.ServiceDesc for DataStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.DataStoreService",
	HandlerType: (*DataStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAreas",
			Handler:    _DataStoreService_GetAreas_Handler,
		},
		{
			MethodName: "ReadBit",
			Handler:    _DataStoreService_ReadBit_Handler,
		},
		{
			MethodName: "WriteBit",
			Handler:    _DataStoreService_WriteBit_Handler,
		},
		{
			MethodName: "ReadBits",
			Handler:    _DataStoreService_ReadBits_Handler,
		},
		{
			MethodName: "WriteBits",
			Handler:    _DataStoreService_WriteBits_Handler,
		},
		{
			MethodName: "ReadWord",
			Handler:    _DataStoreService_ReadWord_Handler,
		},
		{
			MethodName: "WriteWord",
			Handler:    _DataStoreService_WriteWord_Handler,
		},
		{
			MethodName: "ReadWords",
			Handler:    _DataStoreService_ReadWords_Handler,
		},
		{
			MethodName: "WriteWords",
			Handler:    _DataStoreService_WriteWords_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _DataStoreService_Snapshot_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _DataStoreService_Restore_Handler,
		},
		{
			MethodName: "ClearAll",
			Handler:    _DataStoreService_ClearAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeChanges",
			Handler:       _DataStoreService_SubscribeChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "datastore_service.proto",
}
