// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.34.0
// source: datastore_service.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryArea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName    string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsBit          bool   `protobuf:"varint,3,opt,name=is_bit,json=isBit,proto3" json:"is_bit,omitempty"`
	Size           uint32 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ReadOnly       bool   `protobuf:"varint,5,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ByteAddressing bool   `protobuf:"varint,6,opt,name=byte_addressing,json=byteAddressing,proto3" json:"byte_addressing,omitempty"`
	OneOrigin      bool   `protobuf:"varint,7,opt,name=one_origin,json=oneOrigin,proto3" json:"one_origin,omitempty"`
}

func (x *MemoryArea) Reset() {
	*x = MemoryArea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryArea) ProtoMessage() {}

func (x *MemoryArea) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryArea.ProtoReflect.Descriptor instead.
func (*MemoryArea) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryArea) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MemoryArea) GetIsBit() bool {
	if x != nil {
		return x.IsBit
	}
	return false
}

func (x *MemoryArea) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MemoryArea) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *MemoryArea) GetByteAddressing() bool {
	if x != nil {
		return x.ByteAddressing
	}
	return false
}

func (x *MemoryArea) GetOneOrigin() bool {
	if x != nil {
		return x.OneOrigin
	}
	return false
}

type GetAreasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Areas []*MemoryArea `protobuf:"bytes,1,rep,name=areas,proto3" json:"areas,omitempty"`
}

func (x *GetAreasResponse) Reset() {
	*x = GetAreasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreasResponse) ProtoMessage() {}

func (x *GetAreasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreasResponse.ProtoReflect.Descriptor instead.
func (*GetAreasResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAreasResponse) GetAreas() []*MemoryArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

type ReadBitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ReadBitRequest) Reset() {
	*x = ReadBitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBitRequest) ProtoMessage() {}

func (x *ReadBitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBitRequest.ProtoReflect.Descriptor instead.
func (*ReadBitRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBitRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ReadBitRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type ReadBitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReadBitResponse) Reset() {
	*x = ReadBitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBitResponse) ProtoMessage() {}

func (x *ReadBitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBitResponse.ProtoReflect.Descriptor instead.
func (*ReadBitResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBitResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type WriteBitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Value   bool   `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WriteBitRequest) Reset() {
	*x = WriteBitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBitRequest) ProtoMessage() {}

func (x *WriteBitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBitRequest.ProtoReflect.Descriptor instead.
func (*WriteBitRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{4}
}

func (x *WriteBitRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *WriteBitRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *WriteBitRequest) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ReadBitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Count   uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadBitsRequest) Reset() {
	*x = ReadBitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBitsRequest) ProtoMessage() {}

func (x *ReadBitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBitsRequest.ProtoReflect.Descriptor instead.
func (*ReadBitsRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{5}
}

func (x *ReadBitsRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ReadBitsRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *ReadBitsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadBitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []bool `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *ReadBitsResponse) Reset() {
	*x = ReadBitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadBitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBitsResponse) ProtoMessage() {}

func (x *ReadBitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBitsResponse.ProtoReflect.Descriptor instead.
func (*ReadBitsResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{6}
}

func (x *ReadBitsResponse) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type WriteBitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Values  []bool `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *WriteBitsRequest) Reset() {
	*x = WriteBitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBitsRequest) ProtoMessage() {}

func (x *WriteBitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBitsRequest.ProtoReflect.Descriptor instead.
func (*WriteBitsRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{7}
}

func (x *WriteBitsRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *WriteBitsRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *WriteBitsRequest) GetValues() []bool {
	if x != nil {
		return x.Values
	}
	return nil
}

type ReadWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ReadWordRequest) Reset() {
	*x = ReadWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWordRequest) ProtoMessage() {}

func (x *ReadWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWordRequest.ProtoReflect.Descriptor instead.
func (*ReadWordRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{8}
}

func (x *ReadWordRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ReadWordRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type ReadWordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint16 を uint32 で表現
	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ReadWordResponse) Reset() {
	*x = ReadWordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWordResponse) ProtoMessage() {}

func (x *ReadWordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWordResponse.ProtoReflect.Descriptor instead.
func (*ReadWordResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReadWordResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type WriteWordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	// uint16 を uint32 で表現
	Value uint32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WriteWordRequest) Reset() {
	*x = WriteWordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteWordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteWordRequest) ProtoMessage() {}

func (x *WriteWordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteWordRequest.ProtoReflect.Descriptor instead.
func (*WriteWordRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{10}
}

func (x *WriteWordRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *WriteWordRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *WriteWordRequest) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ReadWordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	Count   uint32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ReadWordsRequest) Reset() {
	*x = ReadWordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWordsRequest) ProtoMessage() {}

func (x *ReadWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWordsRequest.ProtoReflect.Descriptor instead.
func (*ReadWordsRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReadWordsRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *ReadWordsRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *ReadWordsRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReadWordsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint16 を uint32 で表現
	Values []uint32 `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *ReadWordsResponse) Reset() {
	*x = ReadWordsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadWordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadWordsResponse) ProtoMessage() {}

func (x *ReadWordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadWordsResponse.ProtoReflect.Descriptor instead.
func (*ReadWordsResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReadWordsResponse) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type WriteWordsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	// uint16 を uint32 で表現
	Values []uint32 `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *WriteWordsRequest) Reset() {
	*x = WriteWordsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteWordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteWordsRequest) ProtoMessage() {}

func (x *WriteWordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteWordsRequest.ProtoReflect.Descriptor instead.
func (*WriteWordsRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{13}
}

func (x *WriteWordsRequest) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *WriteWordsRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *WriteWordsRequest) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// map[string]interface{} を JSON シリアライズ
	SnapshotJson []byte `protobuf:"bytes,1,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotResponse) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

type RestoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnapshotJson []byte `protobuf:"bytes,1,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{15}
}

func (x *RestoreRequest) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

// DataChange: プロトコルクライアントが書き込んだ変更通知
type DataChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area    string `protobuf:"bytes,1,opt,name=area,proto3" json:"area,omitempty"`
	Address uint32 `protobuf:"varint,2,opt,name=address,proto3" json:"address,omitempty"`
	// ワード変更の場合: values に uint16 を uint32 で格納
	Values []uint32 `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	// ビット変更の場合: is_bit=true + bit_values を使用
	IsBit     bool   `protobuf:"varint,4,opt,name=is_bit,json=isBit,proto3" json:"is_bit,omitempty"`
	BitValues []bool `protobuf:"varint,5,rep,packed,name=bit_values,json=bitValues,proto3" json:"bit_values,omitempty"`
}

func (x *DataChange) Reset() {
	*x = DataChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datastore_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChange) ProtoMessage() {}

func (x *DataChange) ProtoReflect() protoreflect.Message {
	mi := &file_datastore_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChange.ProtoReflect.Descriptor instead.
func (*DataChange) Descriptor() ([]byte, []int) {
	return file_datastore_service_proto_rawDescGZIP(), []int{16}
}

func (x *DataChange) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *DataChange) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *DataChange) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *DataChange) GetIsBit() bool {
	if x != nil {
		return x.IsBit
	}
	return false
}

func (x *DataChange) GetBitValues() []bool {
	if x != nil {
		return x.BitValues
	}
	return nil
}

var File_datastore_service_proto protoreflect.FileDescriptor

var file_datastore_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x65,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x62, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x42, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x27, 0x0a, 0x0f,
	0x62, 0x79, 0x74, 0x65, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x62, 0x79, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x6e, 0x65, 0x5f, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x6f, 0x6e, 0x65, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x22, 0x3f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x61, 0x72, 0x65, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x41, 0x72, 0x65, 0x61, 0x52, 0x05,
	0x61, 0x72, 0x65, 0x61, 0x73, 0x22, 0x3e, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x27, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55,
	0x0a, 0x0f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x10,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x08,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x58, 0x0a, 0x10, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x08, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x28, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a,
	0x10, 0x57, 0x72, 0x69, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x10, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2b, 0x0a,
	0x11, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x11, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x37, 0x0a, 0x10, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0c, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x35,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x88, 0x01, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73,
	0x5f, 0x62, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x42, 0x69,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x08, 0x52, 0x09, 0x62, 0x69, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x32, 0xb3, 0x06, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x73, 0x12, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x07, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x12, 0x19, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x69, 0x74, 0x12, 0x1a,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x42, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x08,
	0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3a, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x69, 0x74, 0x73, 0x12, 0x1b,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x42, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a,
	0x08, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x46,
	0x0a, 0x09, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74,
	0x12, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2e, 0x0a, 0x08, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x41, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x6f, 0x64, 0x62, 0x75, 0x73,
	0x5f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_datastore_service_proto_rawDescOnce sync.Once
	file_datastore_service_proto_rawDescData = file_datastore_service_proto_rawDesc
)

func file_datastore_service_proto_rawDescGZIP() []byte {
	file_datastore_service_proto_rawDescOnce.Do(func() {
		file_datastore_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_datastore_service_proto_rawDescData)
	})
	return file_datastore_service_proto_rawDescData
}

var file_datastore_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_datastore_service_proto_goTypes = []interface{}{
	(*MemoryArea)(nil),        // 0: plugin.v1.MemoryArea
	(*GetAreasResponse)(nil),  // 1: plugin.v1.GetAreasResponse
	(*ReadBitRequest)(nil),    // 2: plugin.v1.ReadBitRequest
	(*ReadBitResponse)(nil),   // 3: plugin.v1.ReadBitResponse
	(*WriteBitRequest)(nil),   // 4: plugin.v1.WriteBitRequest
	(*ReadBitsRequest)(nil),   // 5: plugin.v1.ReadBitsRequest
	(*ReadBitsResponse)(nil),  // 6: plugin.v1.ReadBitsResponse
	(*WriteBitsRequest)(nil),  // 7: plugin.v1.WriteBitsRequest
	(*ReadWordRequest)(nil),   // 8: plugin.v1.ReadWordRequest
	(*ReadWordResponse)(nil),  // 9: plugin.v1.ReadWordResponse
	(*WriteWordRequest)(nil),  // 10: plugin.v1.WriteWordRequest
	(*ReadWordsRequest)(nil),  // 11: plugin.v1.ReadWordsRequest
	(*ReadWordsResponse)(nil), // 12: plugin.v1.ReadWordsResponse
	(*WriteWordsRequest)(nil), // 13: plugin.v1.WriteWordsRequest
	(*SnapshotResponse)(nil),  // 14: plugin.v1.SnapshotResponse
	(*RestoreRequest)(nil),    // 15: plugin.v1.RestoreRequest
	(*DataChange)(nil),        // 16: plugin.v1.DataChange
	(*Empty)(nil),             // 17: plugin.v1.Empty
}
var file_datastore_service_proto_depIdxs = []int32{
	0,  // 0: plugin.v1.GetAreasResponse.areas:type_name -> plugin.v1.MemoryArea
	17, // 1: plugin.v1.DataStoreService.GetAreas:input_type -> plugin.v1.Empty
	2,  // 2: plugin.v1.DataStoreService.ReadBit:input_type -> plugin.v1.ReadBitRequest
	4,  // 3: plugin.v1.DataStoreService.WriteBit:input_type -> plugin.v1.WriteBitRequest
	5,  // 4: plugin.v1.DataStoreService.ReadBits:input_type -> plugin.v1.ReadBitsRequest
	7,  // 5: plugin.v1.DataStoreService.WriteBits:input_type -> plugin.v1.WriteBitsRequest
	8,  // 6: plugin.v1.DataStoreService.ReadWord:input_type -> plugin.v1.ReadWordRequest
	10, // 7: plugin.v1.DataStoreService.WriteWord:input_type -> plugin.v1.WriteWordRequest
	11, // 8: plugin.v1.DataStoreService.ReadWords:input_type -> plugin.v1.ReadWordsRequest
	13, // 9: plugin.v1.DataStoreService.WriteWords:input_type -> plugin.v1.WriteWordsRequest
	17, // 10: plugin.v1.DataStoreService.Snapshot:input_type -> plugin.v1.Empty
	15, // 11: plugin.v1.DataStoreService.Restore:input_type -> plugin.v1.RestoreRequest
	17, // 12: plugin.v1.DataStoreService.ClearAll:input_type -> plugin.v1.Empty
	17, // 13: plugin.v1.DataStoreService.SubscribeChanges:input_type -> plugin.v1.Empty
	1,  // 14: plugin.v1.DataStoreService.GetAreas:output_type -> plugin.v1.GetAreasResponse
	3,  // 15: plugin.v1.DataStoreService.ReadBit:output_type -> plugin.v1.ReadBitResponse
	17, // 16: plugin.v1.DataStoreService.WriteBit:output_type -> plugin.v1.Empty
	6,  // 17: plugin.v1.DataStoreService.ReadBits:output_type -> plugin.v1.ReadBitsResponse
	17, // 18: plugin.v1.DataStoreService.WriteBits:output_type -> plugin.v1.Empty
	9,  // 19: plugin.v1.DataStoreService.ReadWord:output_type -> plugin.v1.ReadWordResponse
	17, // 20: plugin.v1.DataStoreService.WriteWord:output_type -> plugin.v1.Empty
	12, // 21: plugin.v1.DataStoreService.ReadWords:output_type -> plugin.v1.ReadWordsResponse
	17, // 22: plugin.v1.DataStoreService.WriteWords:output_type -> plugin.v1.Empty
	14, // 23: plugin.v1.DataStoreService.Snapshot:output_type -> plugin.v1.SnapshotResponse
	17, // 24: plugin.v1.DataStoreService.Restore:output_type -> plugin.v1.Empty
	17, // 25: plugin.v1.DataStoreService.ClearAll:output_type -> plugin.v1.Empty
	16, // 26: plugin.v1.DataStoreService.SubscribeChanges:output_type -> plugin.v1.DataChange
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_datastore_service_proto_init() }
func file_datastore_service_proto_init() {
	if File_datastore_service_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_datastore_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryArea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadBitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteWordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadWordsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteWordsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_datastore_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datastore_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datastore_service_proto_goTypes,
		DependencyIndexes: file_datastore_service_proto_depIdxs,
		MessageInfos:      file_datastore_service_proto_msgTypes,
	}.Build()
	File_datastore_service_proto = out.File
	file_datastore_service_proto_rawDesc = nil
	file_datastore_service_proto_goTypes = nil
	file_datastore_service_proto_depIdxs = nil
}
