// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.0
// source: plugin_service.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// ファクトリー系（メタデータ・スキーマ）
	GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginMetadata, error)
	GetConfigVariants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigVariantsResponse, error)
	GetConfigFields(ctx context.Context, in *GetConfigFieldsRequest, opts ...grpc.CallOption) (*GetConfigFieldsResponse, error)
	GetDefaultConfig(ctx context.Context, in *GetDefaultConfigRequest, opts ...grpc.CallOption) (*ConfigDataResponse, error)
	MapToConfig(ctx context.Context, in *MapToConfigRequest, opts ...grpc.CallOption) (*MapToConfigResponse, error)
	ConfigToMap(ctx context.Context, in *ConfigToMapRequest, opts ...grpc.CallOption) (*ConfigToMapResponse, error)
	// サーバーライフサイクル
	// CreateAndStart: サーバーを作成して起動する。host_grpc_addr は
	// SupportsNodePublishing=true の場合に VariableAccessorService への接続先として使用する
	CreateAndStart(ctx context.Context, in *CreateAndStartRequest, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*Empty, error)
	// ノード公開設定変更通知（SupportsNodePublishing=true のプロトコル用）
	OnNodePublishingUpdated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// UnitID 管理（SupportsUnitID=true のプロトコル用）
	GetUnitIDSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnitIDSettingsResponse, error)
	SetUnitIDEnabled(ctx context.Context, in *SetUnitIDEnabledRequest, opts ...grpc.CallOption) (*Empty, error)
	SetDisabledUnitIDs(ctx context.Context, in *SetDisabledUnitIDsRequest, opts ...grpc.CallOption) (*Empty, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) GetMetadata(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginMetadata, error) {
	out := new(PluginMetadata)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetConfigVariants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetConfigVariantsResponse, error) {
	out := new(GetConfigVariantsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetConfigVariants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetConfigFields(ctx context.Context, in *GetConfigFieldsRequest, opts ...grpc.CallOption) (*GetConfigFieldsResponse, error) {
	out := new(GetConfigFieldsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetConfigFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetDefaultConfig(ctx context.Context, in *GetDefaultConfigRequest, opts ...grpc.CallOption) (*ConfigDataResponse, error) {
	out := new(ConfigDataResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetDefaultConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) MapToConfig(ctx context.Context, in *MapToConfigRequest, opts ...grpc.CallOption) (*MapToConfigResponse, error) {
	out := new(MapToConfigResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/MapToConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ConfigToMap(ctx context.Context, in *ConfigToMapRequest, opts ...grpc.CallOption) (*ConfigToMapResponse, error) {
	out := new(ConfigToMapResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/ConfigToMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CreateAndStart(ctx context.Context, in *CreateAndStartRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/CreateAndStart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) OnNodePublishingUpdated(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/OnNodePublishingUpdated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetUnitIDSettings(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*UnitIDSettingsResponse, error) {
	out := new(UnitIDSettingsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/GetUnitIDSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) SetUnitIDEnabled(ctx context.Context, in *SetUnitIDEnabledRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/SetUnitIDEnabled", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) SetDisabledUnitIDs(ctx context.Context, in *SetDisabledUnitIDsRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.PluginService/SetDisabledUnitIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	// ファクトリー系（メタデータ・スキーマ）
	GetMetadata(context.Context, *Empty) (*PluginMetadata, error)
	GetConfigVariants(context.Context, *Empty) (*GetConfigVariantsResponse, error)
	GetConfigFields(context.Context, *GetConfigFieldsRequest) (*GetConfigFieldsResponse, error)
	GetDefaultConfig(context.Context, *GetDefaultConfigRequest) (*ConfigDataResponse, error)
	MapToConfig(context.Context, *MapToConfigRequest) (*MapToConfigResponse, error)
	ConfigToMap(context.Context, *ConfigToMapRequest) (*ConfigToMapResponse, error)
	// サーバーライフサイクル
	// CreateAndStart: サーバーを作成して起動する。host_grpc_addr は
	// SupportsNodePublishing=true の場合に VariableAccessorService への接続先として使用する
	CreateAndStart(context.Context, *CreateAndStartRequest) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*Empty, error)
	// ノード公開設定変更通知（SupportsNodePublishing=true のプロトコル用）
	OnNodePublishingUpdated(context.Context, *Empty) (*Empty, error)
	// UnitID 管理（SupportsUnitID=true のプロトコル用）
	GetUnitIDSettings(context.Context, *Empty) (*UnitIDSettingsResponse, error)
	SetUnitIDEnabled(context.Context, *SetUnitIDEnabledRequest) (*Empty, error)
	SetDisabledUnitIDs(context.Context, *SetDisabledUnitIDsRequest) (*Empty, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) GetMetadata(context.Context, *Empty) (*PluginMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedPluginServiceServer) GetConfigVariants(context.Context, *Empty) (*GetConfigVariantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigVariants not implemented")
}
func (UnimplementedPluginServiceServer) GetConfigFields(context.Context, *GetConfigFieldsRequest) (*GetConfigFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigFields not implemented")
}
func (UnimplementedPluginServiceServer) GetDefaultConfig(context.Context, *GetDefaultConfigRequest) (*ConfigDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDefaultConfig not implemented")
}
func (UnimplementedPluginServiceServer) MapToConfig(context.Context, *MapToConfigRequest) (*MapToConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapToConfig not implemented")
}
func (UnimplementedPluginServiceServer) ConfigToMap(context.Context, *ConfigToMapRequest) (*ConfigToMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigToMap not implemented")
}
func (UnimplementedPluginServiceServer) CreateAndStart(context.Context, *CreateAndStartRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAndStart not implemented")
}
func (UnimplementedPluginServiceServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginServiceServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPluginServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedPluginServiceServer) OnNodePublishingUpdated(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnNodePublishingUpdated not implemented")
}
func (UnimplementedPluginServiceServer) GetUnitIDSettings(context.Context, *Empty) (*UnitIDSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnitIDSettings not implemented")
}
func (UnimplementedPluginServiceServer) SetUnitIDEnabled(context.Context, *SetUnitIDEnabledRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUnitIDEnabled not implemented")
}
func (UnimplementedPluginServiceServer) SetDisabledUnitIDs(context.Context, *SetDisabledUnitIDsRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDisabledUnitIDs not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetMetadata(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetConfigVariants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetConfigVariants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetConfigVariants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetConfigVariants(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetConfigFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetConfigFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetConfigFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetConfigFields(ctx, req.(*GetConfigFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetDefaultConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetDefaultConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetDefaultConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetDefaultConfig(ctx, req.(*GetDefaultConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_MapToConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapToConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).MapToConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/MapToConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).MapToConfig(ctx, req.(*MapToConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ConfigToMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigToMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ConfigToMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/ConfigToMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ConfigToMap(ctx, req.(*ConfigToMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CreateAndStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAndStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CreateAndStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/CreateAndStart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CreateAndStart(ctx, req.(*CreateAndStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_OnNodePublishingUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).OnNodePublishingUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/OnNodePublishingUpdated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).OnNodePublishingUpdated(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetUnitIDSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetUnitIDSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/GetUnitIDSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetUnitIDSettings(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_SetUnitIDEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUnitIDEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).SetUnitIDEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/SetUnitIDEnabled",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).SetUnitIDEnabled(ctx, req.(*SetUnitIDEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_SetDisabledUnitIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDisabledUnitIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).SetDisabledUnitIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.PluginService/SetDisabledUnitIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).SetDisabledUnitIDs(ctx, req.(*SetDisabledUnitIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _PluginService_GetMetadata_Handler,
		},
		{
			MethodName: "GetConfigVariants",
			Handler:    _PluginService_GetConfigVariants_Handler,
		},
		{
			MethodName: "GetConfigFields",
			Handler:    _PluginService_GetConfigFields_Handler,
		},
		{
			MethodName: "GetDefaultConfig",
			Handler:    _PluginService_GetDefaultConfig_Handler,
		},
		{
			MethodName: "MapToConfig",
			Handler:    _PluginService_MapToConfig_Handler,
		},
		{
			MethodName: "ConfigToMap",
			Handler:    _PluginService_ConfigToMap_Handler,
		},
		{
			MethodName: "CreateAndStart",
			Handler:    _PluginService_CreateAndStart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginService_Stop_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PluginService_GetStatus_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _PluginService_UpdateConfig_Handler,
		},
		{
			MethodName: "OnNodePublishingUpdated",
			Handler:    _PluginService_OnNodePublishingUpdated_Handler,
		},
		{
			MethodName: "GetUnitIDSettings",
			Handler:    _PluginService_GetUnitIDSettings_Handler,
		},
		{
			MethodName: "SetUnitIDEnabled",
			Handler:    _PluginService_SetUnitIDEnabled_Handler,
		},
		{
			MethodName: "SetDisabledUnitIDs",
			Handler:    _PluginService_SetDisabledUnitIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin_service.proto",
}
