// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.0
// source: variable_accessor_service.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VariableAccessorServiceClient is the client API for VariableAccessorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VariableAccessorServiceClient interface {
	GetEnabledNodePublishings(ctx context.Context, in *GetNodePublishingsRequest, opts ...grpc.CallOption) (*GetNodePublishingsResponse, error)
	// value_msgpack には変数値を MessagePack シリアライズしたバイト列を使用する（uint64 精度を保持）
	ReadVariableValue(ctx context.Context, in *ReadVariableValueRequest, opts ...grpc.CallOption) (*ReadVariableValueResponse, error)
	WriteVariableValue(ctx context.Context, in *WriteVariableValueRequest, opts ...grpc.CallOption) (*Empty, error)
	// WriteVariableField は変数の特定フィールド/要素のみをアトミックに更新する。
	// field_path は外部インデックス（表示ベース）のパス文字列
	// 例: "motor.speed", "items[1]"（ARRAY[1..10] の場合）, "items[2].name"
	WriteVariableField(ctx context.Context, in *WriteVariableFieldRequest, opts ...grpc.CallOption) (*Empty, error)
	GetStructFields(ctx context.Context, in *GetStructFieldsRequest, opts ...grpc.CallOption) (*GetStructFieldsResponse, error)
	// SubscribeVariableChanges: ホストの VariableStore 変更をプラグインに通知する
	// OPC UA サブスクリプション更新等に使用する
	SubscribeVariableChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (VariableAccessorService_SubscribeVariableChangesClient, error)
}

type variableAccessorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVariableAccessorServiceClient(cc grpc.ClientConnInterface) VariableAccessorServiceClient {
	return &variableAccessorServiceClient{cc}
}

func (c *variableAccessorServiceClient) GetEnabledNodePublishings(ctx context.Context, in *GetNodePublishingsRequest, opts ...grpc.CallOption) (*GetNodePublishingsResponse, error) {
	out := new(GetNodePublishingsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.VariableAccessorService/GetEnabledNodePublishings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableAccessorServiceClient) ReadVariableValue(ctx context.Context, in *ReadVariableValueRequest, opts ...grpc.CallOption) (*ReadVariableValueResponse, error) {
	out := new(ReadVariableValueResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.VariableAccessorService/ReadVariableValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableAccessorServiceClient) WriteVariableValue(ctx context.Context, in *WriteVariableValueRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.VariableAccessorService/WriteVariableValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableAccessorServiceClient) WriteVariableField(ctx context.Context, in *WriteVariableFieldRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/plugin.v1.VariableAccessorService/WriteVariableField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableAccessorServiceClient) GetStructFields(ctx context.Context, in *GetStructFieldsRequest, opts ...grpc.CallOption) (*GetStructFieldsResponse, error) {
	out := new(GetStructFieldsResponse)
	err := c.cc.Invoke(ctx, "/plugin.v1.VariableAccessorService/GetStructFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableAccessorServiceClient) SubscribeVariableChanges(ctx context.Context, in *Empty, opts ...grpc.CallOption) (VariableAccessorService_SubscribeVariableChangesClient, error) {
	stream, err := c.cc.NewStream(ctx, &VariableAccessorService_ServiceDesc.Streams[0], "/plugin.v1.VariableAccessorService/SubscribeVariableChanges", opts...)
	if err != nil {
		return nil, err
	}
	x := &variableAccessorServiceSubscribeVariableChangesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type VariableAccessorService_SubscribeVariableChangesClient interface {
	Recv() (*VariableChange, error)
	grpc.ClientStream
}

type variableAccessorServiceSubscribeVariableChangesClient struct {
	grpc.ClientStream
}

func (x *variableAccessorServiceSubscribeVariableChangesClient) Recv() (*VariableChange, error) {
	m := new(VariableChange)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// VariableAccessorServiceServer is the server API for VariableAccessorService service.
// All implementations must embed UnimplementedVariableAccessorServiceServer
// for forward compatibility
type VariableAccessorServiceServer interface {
	GetEnabledNodePublishings(context.Context, *GetNodePublishingsRequest) (*GetNodePublishingsResponse, error)
	// value_msgpack には変数値を MessagePack シリアライズしたバイト列を使用する（uint64 精度を保持）
	ReadVariableValue(context.Context, *ReadVariableValueRequest) (*ReadVariableValueResponse, error)
	WriteVariableValue(context.Context, *WriteVariableValueRequest) (*Empty, error)
	// WriteVariableField は変数の特定フィールド/要素のみをアトミックに更新する。
	// field_path は外部インデックス（表示ベース）のパス文字列
	// 例: "motor.speed", "items[1]"（ARRAY[1..10] の場合）, "items[2].name"
	WriteVariableField(context.Context, *WriteVariableFieldRequest) (*Empty, error)
	GetStructFields(context.Context, *GetStructFieldsRequest) (*GetStructFieldsResponse, error)
	// SubscribeVariableChanges: ホストの VariableStore 変更をプラグインに通知する
	// OPC UA サブスクリプション更新等に使用する
	SubscribeVariableChanges(*Empty, VariableAccessorService_SubscribeVariableChangesServer) error
	mustEmbedUnimplementedVariableAccessorServiceServer()
}

// UnimplementedVariableAccessorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVariableAccessorServiceServer struct {
}

func (UnimplementedVariableAccessorServiceServer) GetEnabledNodePublishings(context.Context, *GetNodePublishingsRequest) (*GetNodePublishingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnabledNodePublishings not implemented")
}
func (UnimplementedVariableAccessorServiceServer) ReadVariableValue(context.Context, *ReadVariableValueRequest) (*ReadVariableValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadVariableValue not implemented")
}
func (UnimplementedVariableAccessorServiceServer) WriteVariableValue(context.Context, *WriteVariableValueRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteVariableValue not implemented")
}
func (UnimplementedVariableAccessorServiceServer) WriteVariableField(context.Context, *WriteVariableFieldRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteVariableField not implemented")
}
func (UnimplementedVariableAccessorServiceServer) GetStructFields(context.Context, *GetStructFieldsRequest) (*GetStructFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStructFields not implemented")
}
func (UnimplementedVariableAccessorServiceServer) SubscribeVariableChanges(*Empty, VariableAccessorService_SubscribeVariableChangesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeVariableChanges not implemented")
}
func (UnimplementedVariableAccessorServiceServer) mustEmbedUnimplementedVariableAccessorServiceServer() {
}

// UnsafeVariableAccessorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VariableAccessorServiceServer will
// result in compilation errors.
type UnsafeVariableAccessorServiceServer interface {
	mustEmbedUnimplementedVariableAccessorServiceServer()
}

func RegisterVariableAccessorServiceServer(s grpc.ServiceRegistrar, srv VariableAccessorServiceServer) {
	s.RegisterService(&VariableAccessorService_ServiceDesc, srv)
}

func _VariableAccessorService_GetEnabledNodePublishings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodePublishingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableAccessorServiceServer).GetEnabledNodePublishings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.VariableAccessorService/GetEnabledNodePublishings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableAccessorServiceServer).GetEnabledNodePublishings(ctx, req.(*GetNodePublishingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableAccessorService_ReadVariableValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVariableValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableAccessorServiceServer).ReadVariableValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.VariableAccessorService/ReadVariableValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableAccessorServiceServer).ReadVariableValue(ctx, req.(*ReadVariableValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableAccessorService_WriteVariableValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVariableValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableAccessorServiceServer).WriteVariableValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.VariableAccessorService/WriteVariableValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableAccessorServiceServer).WriteVariableValue(ctx, req.(*WriteVariableValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableAccessorService_WriteVariableField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteVariableFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableAccessorServiceServer).WriteVariableField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.VariableAccessorService/WriteVariableField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableAccessorServiceServer).WriteVariableField(ctx, req.(*WriteVariableFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableAccessorService_GetStructFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStructFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableAccessorServiceServer).GetStructFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/plugin.v1.VariableAccessorService/GetStructFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableAccessorServiceServer).GetStructFields(ctx, req.(*GetStructFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableAccessorService_SubscribeVariableChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VariableAccessorServiceServer).SubscribeVariableChanges(m, &variableAccessorServiceSubscribeVariableChangesServer{stream})
}

type VariableAccessorService_SubscribeVariableChangesServer interface {
	Send(*VariableChange) error
	grpc.ServerStream
}

type variableAccessorServiceSubscribeVariableChangesServer struct {
	grpc.ServerStream
}

func (x *variableAccessorServiceSubscribeVariableChangesServer) Send(m *VariableChange) error {
	return x.ServerStream.SendMsg(m)
}

// VariableAccessorService_ServiceDesc is the grpc.ServiceDesc for VariableAccessorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VariableAccessorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.VariableAccessorService",
	HandlerType: (*VariableAccessorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnabledNodePublishings",
			Handler:    _VariableAccessorService_GetEnabledNodePublishings_Handler,
		},
		{
			MethodName: "ReadVariableValue",
			Handler:    _VariableAccessorService_ReadVariableValue_Handler,
		},
		{
			MethodName: "WriteVariableValue",
			Handler:    _VariableAccessorService_WriteVariableValue_Handler,
		},
		{
			MethodName: "WriteVariableField",
			Handler:    _VariableAccessorService_WriteVariableField_Handler,
		},
		{
			MethodName: "GetStructFields",
			Handler:    _VariableAccessorService_GetStructFields_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeVariableChanges",
			Handler:       _VariableAccessorService_SubscribeVariableChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "variable_accessor_service.proto",
}
