// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.34.0
// source: variable_accessor_service.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodePublishingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProtocolType string `protobuf:"bytes,1,opt,name=protocol_type,json=protocolType,proto3" json:"protocol_type,omitempty"`
}

func (x *GetNodePublishingsRequest) Reset() {
	*x = GetNodePublishingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodePublishingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodePublishingsRequest) ProtoMessage() {}

func (x *GetNodePublishingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodePublishingsRequest.ProtoReflect.Descriptor instead.
func (*GetNodePublishingsRequest) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetNodePublishingsRequest) GetProtocolType() string {
	if x != nil {
		return x.ProtocolType
	}
	return ""
}

type NodePublishingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VariableId   string `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	VariableName string `protobuf:"bytes,2,opt,name=variable_name,json=variableName,proto3" json:"variable_name,omitempty"`
	DataType     string `protobuf:"bytes,3,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`       // "INT", "REAL", "STRING[20]" 等
	AccessMode   string `protobuf:"bytes,4,opt,name=access_mode,json=accessMode,proto3" json:"access_mode,omitempty"` // "read", "write", "readwrite"
}

func (x *NodePublishingInfo) Reset() {
	*x = NodePublishingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodePublishingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePublishingInfo) ProtoMessage() {}

func (x *NodePublishingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePublishingInfo.ProtoReflect.Descriptor instead.
func (*NodePublishingInfo) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{1}
}

func (x *NodePublishingInfo) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

func (x *NodePublishingInfo) GetVariableName() string {
	if x != nil {
		return x.VariableName
	}
	return ""
}

func (x *NodePublishingInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *NodePublishingInfo) GetAccessMode() string {
	if x != nil {
		return x.AccessMode
	}
	return ""
}

type GetNodePublishingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Publishings []*NodePublishingInfo `protobuf:"bytes,1,rep,name=publishings,proto3" json:"publishings,omitempty"`
}

func (x *GetNodePublishingsResponse) Reset() {
	*x = GetNodePublishingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodePublishingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodePublishingsResponse) ProtoMessage() {}

func (x *GetNodePublishingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodePublishingsResponse.ProtoReflect.Descriptor instead.
func (*GetNodePublishingsResponse) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodePublishingsResponse) GetPublishings() []*NodePublishingInfo {
	if x != nil {
		return x.Publishings
	}
	return nil
}

type ReadVariableValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VariableId string `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
}

func (x *ReadVariableValueRequest) Reset() {
	*x = ReadVariableValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadVariableValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVariableValueRequest) ProtoMessage() {}

func (x *ReadVariableValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVariableValueRequest.ProtoReflect.Descriptor instead.
func (*ReadVariableValueRequest) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReadVariableValueRequest) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

type ReadVariableValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 変数値を JSON シリアライズした文字列
	ValueJson string `protobuf:"bytes,1,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	Error     string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 空文字列ならエラーなし
}

func (x *ReadVariableValueResponse) Reset() {
	*x = ReadVariableValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadVariableValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadVariableValueResponse) ProtoMessage() {}

func (x *ReadVariableValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadVariableValueResponse.ProtoReflect.Descriptor instead.
func (*ReadVariableValueResponse) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReadVariableValueResponse) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *ReadVariableValueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteVariableValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VariableId string `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	ValueJson  string `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
}

func (x *WriteVariableValueRequest) Reset() {
	*x = WriteVariableValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteVariableValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteVariableValueRequest) ProtoMessage() {}

func (x *WriteVariableValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteVariableValueRequest.ProtoReflect.Descriptor instead.
func (*WriteVariableValueRequest) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{5}
}

func (x *WriteVariableValueRequest) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

func (x *WriteVariableValueRequest) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type GetStructFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
}

func (x *GetStructFieldsRequest) Reset() {
	*x = GetStructFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStructFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStructFieldsRequest) ProtoMessage() {}

func (x *GetStructFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStructFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetStructFieldsRequest) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetStructFieldsRequest) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

type StructFieldInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType string `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
}

func (x *StructFieldInfo) Reset() {
	*x = StructFieldInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructFieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructFieldInfo) ProtoMessage() {}

func (x *StructFieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructFieldInfo.ProtoReflect.Descriptor instead.
func (*StructFieldInfo) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{7}
}

func (x *StructFieldInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StructFieldInfo) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

type GetStructFieldsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*StructFieldInfo `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *GetStructFieldsResponse) Reset() {
	*x = GetStructFieldsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStructFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStructFieldsResponse) ProtoMessage() {}

func (x *GetStructFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStructFieldsResponse.ProtoReflect.Descriptor instead.
func (*GetStructFieldsResponse) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetStructFieldsResponse) GetFields() []*StructFieldInfo {
	if x != nil {
		return x.Fields
	}
	return nil
}

// VariableChange: ホストの VariableStore 変更通知
type VariableChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VariableId string `protobuf:"bytes,1,opt,name=variable_id,json=variableId,proto3" json:"variable_id,omitempty"`
	ValueJson  string `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
}

func (x *VariableChange) Reset() {
	*x = VariableChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variable_accessor_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableChange) ProtoMessage() {}

func (x *VariableChange) ProtoReflect() protoreflect.Message {
	mi := &file_variable_accessor_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableChange.ProtoReflect.Descriptor instead.
func (*VariableChange) Descriptor() ([]byte, []int) {
	return file_variable_accessor_service_proto_rawDescGZIP(), []int{9}
}

func (x *VariableChange) GetVariableId() string {
	if x != nil {
		return x.VariableId
	}
	return ""
}

func (x *VariableChange) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

var File_variable_accessor_service_proto protoreflect.FileDescriptor

var file_variable_accessor_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x22, 0x98, 0x01, 0x0a,
	0x12, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x5d, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x3b, 0x0a, 0x18, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x19, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5b, 0x0a, 0x19, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6a, 0x73, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4a, 0x73,
	0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0f, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4d, 0x0a,
	0x17, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x50, 0x0a, 0x0e,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4a, 0x73, 0x6f, 0x6e, 0x32, 0xd6,
	0x03, 0x0a, 0x17, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x68, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64,
	0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x12, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x24, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x58, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x21, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x18,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x10, 0x2e, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x30, 0x01, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x6f, 0x64, 0x62, 0x75,
	0x73, 0x5f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_variable_accessor_service_proto_rawDescOnce sync.Once
	file_variable_accessor_service_proto_rawDescData = file_variable_accessor_service_proto_rawDesc
)

func file_variable_accessor_service_proto_rawDescGZIP() []byte {
	file_variable_accessor_service_proto_rawDescOnce.Do(func() {
		file_variable_accessor_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_variable_accessor_service_proto_rawDescData)
	})
	return file_variable_accessor_service_proto_rawDescData
}

var file_variable_accessor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_variable_accessor_service_proto_goTypes = []interface{}{
	(*GetNodePublishingsRequest)(nil),  // 0: plugin.v1.GetNodePublishingsRequest
	(*NodePublishingInfo)(nil),         // 1: plugin.v1.NodePublishingInfo
	(*GetNodePublishingsResponse)(nil), // 2: plugin.v1.GetNodePublishingsResponse
	(*ReadVariableValueRequest)(nil),   // 3: plugin.v1.ReadVariableValueRequest
	(*ReadVariableValueResponse)(nil),  // 4: plugin.v1.ReadVariableValueResponse
	(*WriteVariableValueRequest)(nil),  // 5: plugin.v1.WriteVariableValueRequest
	(*GetStructFieldsRequest)(nil),     // 6: plugin.v1.GetStructFieldsRequest
	(*StructFieldInfo)(nil),            // 7: plugin.v1.StructFieldInfo
	(*GetStructFieldsResponse)(nil),    // 8: plugin.v1.GetStructFieldsResponse
	(*VariableChange)(nil),             // 9: plugin.v1.VariableChange
	(*Empty)(nil),                      // 10: plugin.v1.Empty
}
var file_variable_accessor_service_proto_depIdxs = []int32{
	1,  // 0: plugin.v1.GetNodePublishingsResponse.publishings:type_name -> plugin.v1.NodePublishingInfo
	7,  // 1: plugin.v1.GetStructFieldsResponse.fields:type_name -> plugin.v1.StructFieldInfo
	0,  // 2: plugin.v1.VariableAccessorService.GetEnabledNodePublishings:input_type -> plugin.v1.GetNodePublishingsRequest
	3,  // 3: plugin.v1.VariableAccessorService.ReadVariableValue:input_type -> plugin.v1.ReadVariableValueRequest
	5,  // 4: plugin.v1.VariableAccessorService.WriteVariableValue:input_type -> plugin.v1.WriteVariableValueRequest
	6,  // 5: plugin.v1.VariableAccessorService.GetStructFields:input_type -> plugin.v1.GetStructFieldsRequest
	10, // 6: plugin.v1.VariableAccessorService.SubscribeVariableChanges:input_type -> plugin.v1.Empty
	2,  // 7: plugin.v1.VariableAccessorService.GetEnabledNodePublishings:output_type -> plugin.v1.GetNodePublishingsResponse
	4,  // 8: plugin.v1.VariableAccessorService.ReadVariableValue:output_type -> plugin.v1.ReadVariableValueResponse
	10, // 9: plugin.v1.VariableAccessorService.WriteVariableValue:output_type -> plugin.v1.Empty
	8,  // 10: plugin.v1.VariableAccessorService.GetStructFields:output_type -> plugin.v1.GetStructFieldsResponse
	9,  // 11: plugin.v1.VariableAccessorService.SubscribeVariableChanges:output_type -> plugin.v1.VariableChange
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_variable_accessor_service_proto_init() }
func file_variable_accessor_service_proto_init() {
	if File_variable_accessor_service_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_variable_accessor_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodePublishingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodePublishingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodePublishingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadVariableValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadVariableValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteVariableValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStructFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructFieldInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStructFieldsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_variable_accessor_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_variable_accessor_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_variable_accessor_service_proto_goTypes,
		DependencyIndexes: file_variable_accessor_service_proto_depIdxs,
		MessageInfos:      file_variable_accessor_service_proto_msgTypes,
	}.Build()
	File_variable_accessor_service_proto = out.File
	file_variable_accessor_service_proto_rawDesc = nil
	file_variable_accessor_service_proto_goTypes = nil
	file_variable_accessor_service_proto_depIdxs = nil
}
