// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScript'](arg1, arg2, arg3);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function GetCoils(arg1, arg2) {
  return window['go']['main']['App']['GetCoils'](arg1, arg2);
}

export function GetDiscreteInputs(arg1, arg2) {
  return window['go']['main']['App']['GetDiscreteInputs'](arg1, arg2);
}

export function GetHoldingRegisters(arg1, arg2) {
  return window['go']['main']['App']['GetHoldingRegisters'](arg1, arg2);
}

export function GetInputRegisters(arg1, arg2) {
  return window['go']['main']['App']['GetInputRegisters'](arg1, arg2);
}

export function GetIntervalPresets() {
  return window['go']['main']['App']['GetIntervalPresets']();
}

export function GetScript(arg1) {
  return window['go']['main']['App']['GetScript'](arg1);
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetServerConfig() {
  return window['go']['main']['App']['GetServerConfig']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function RunScriptOnce(arg1) {
  return window['go']['main']['App']['RunScriptOnce'](arg1);
}

export function SetCoil(arg1, arg2) {
  return window['go']['main']['App']['SetCoil'](arg1, arg2);
}

export function SetDiscreteInput(arg1, arg2) {
  return window['go']['main']['App']['SetDiscreteInput'](arg1, arg2);
}

export function SetHoldingRegister(arg1, arg2) {
  return window['go']['main']['App']['SetHoldingRegister'](arg1, arg2);
}

export function SetInputRegister(arg1, arg2) {
  return window['go']['main']['App']['SetInputRegister'](arg1, arg2);
}

export function StartScript(arg1) {
  return window['go']['main']['App']['StartScript'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2, arg3, arg4);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}
