// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';

export function CreateScript(arg1:string,arg2:string,arg3:number):Promise<application.ScriptDTO>;

export function DeleteScript(arg1:string):Promise<void>;

export function ExportProject():Promise<void>;

export function GetActiveProtocol():Promise<string>;

export function GetActiveVariant():Promise<string>;

export function GetAvailableProtocols():Promise<Array<application.ProtocolInfoDTO>>;

export function GetCurrentConfig():Promise<application.ProtocolConfigDTO>;

export function GetDisabledUnitIDs():Promise<Array<number>>;

export function GetIntervalPresets():Promise<Array<application.IntervalPresetDTO>>;

export function GetMemoryAreas():Promise<Array<application.MemoryAreaDTO>>;

export function GetProtocolSchema(arg1:string):Promise<application.ProtocolSchemaDTO>;

export function GetScript(arg1:string):Promise<application.ScriptDTO>;

export function GetScripts():Promise<Array<application.ScriptDTO>>;

export function GetSerialPorts():Promise<Array<string>>;

export function GetServerStatus():Promise<string>;

export function GetUnitIDSettings():Promise<application.UnitIDSettingsDTO>;

export function ImportProject():Promise<void>;

export function ReadBits(arg1:string,arg2:number,arg3:number):Promise<Array<boolean>>;

export function ReadWords(arg1:string,arg2:number,arg3:number):Promise<Array<number>>;

export function RunScriptOnce(arg1:string):Promise<any>;

export function SetDisabledUnitIDs(arg1:Array<number>):Promise<void>;

export function SetProtocol(arg1:string,arg2:string):Promise<void>;

export function SetUnitIDEnabled(arg1:number,arg2:boolean):Promise<void>;

export function StartScript(arg1:string):Promise<void>;

export function StartServer():Promise<void>;

export function StopScript(arg1:string):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateConfig(arg1:application.ProtocolConfigDTO):Promise<void>;

export function UpdateScript(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function WriteBit(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function WriteWord(arg1:string,arg2:number,arg3:number):Promise<void>;
