// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitoringItem(arg1) {
  return window['go']['main']['App']['AddMonitoringItem'](arg1);
}

export function ClearMonitoringItems() {
  return window['go']['main']['App']['ClearMonitoringItems']();
}

export function CreateScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScript'](arg1, arg2, arg3);
}

export function DeleteMonitoringItem(arg1) {
  return window['go']['main']['App']['DeleteMonitoringItem'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function ExportProject() {
  return window['go']['main']['App']['ExportProject']();
}

export function GetActiveProtocol() {
  return window['go']['main']['App']['GetActiveProtocol']();
}

export function GetActiveVariant() {
  return window['go']['main']['App']['GetActiveVariant']();
}

export function GetAvailableProtocols() {
  return window['go']['main']['App']['GetAvailableProtocols']();
}

export function GetCurrentConfig() {
  return window['go']['main']['App']['GetCurrentConfig']();
}

export function GetDisabledUnitIDs() {
  return window['go']['main']['App']['GetDisabledUnitIDs']();
}

export function GetIntervalPresets() {
  return window['go']['main']['App']['GetIntervalPresets']();
}

export function GetMemoryAreas() {
  return window['go']['main']['App']['GetMemoryAreas']();
}

export function GetMonitoringItems() {
  return window['go']['main']['App']['GetMonitoringItems']();
}

export function GetProtocolSchema(arg1) {
  return window['go']['main']['App']['GetProtocolSchema'](arg1);
}

export function GetScript(arg1) {
  return window['go']['main']['App']['GetScript'](arg1);
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetUnitIDSettings() {
  return window['go']['main']['App']['GetUnitIDSettings']();
}

export function ImportProject() {
  return window['go']['main']['App']['ImportProject']();
}

export function MoveMonitoringItem(arg1, arg2) {
  return window['go']['main']['App']['MoveMonitoringItem'](arg1, arg2);
}

export function ReadBits(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadBits'](arg1, arg2, arg3);
}

export function ReadWords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadWords'](arg1, arg2, arg3);
}

export function ReorderMonitoringItem(arg1, arg2) {
  return window['go']['main']['App']['ReorderMonitoringItem'](arg1, arg2);
}

export function RunScriptOnce(arg1) {
  return window['go']['main']['App']['RunScriptOnce'](arg1);
}

export function SetDisabledUnitIDs(arg1) {
  return window['go']['main']['App']['SetDisabledUnitIDs'](arg1);
}

export function SetProtocol(arg1, arg2) {
  return window['go']['main']['App']['SetProtocol'](arg1, arg2);
}

export function SetUnitIDEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetUnitIDEnabled'](arg1, arg2);
}

export function StartScript(arg1) {
  return window['go']['main']['App']['StartScript'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateMonitoringItem(arg1) {
  return window['go']['main']['App']['UpdateMonitoringItem'](arg1);
}

export function UpdateScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2, arg3, arg4);
}

export function WriteBit(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteBit'](arg1, arg2, arg3);
}

export function WriteWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteWord'](arg1, arg2, arg3);
}
