// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitoringItem(arg1) {
  return window['go']['main']['App']['AddMonitoringItem'](arg1);
}

export function AddServer(arg1, arg2) {
  return window['go']['main']['App']['AddServer'](arg1, arg2);
}

export function ClearConsoleLogs() {
  return window['go']['main']['App']['ClearConsoleLogs']();
}

export function ClearMonitoringItems() {
  return window['go']['main']['App']['ClearMonitoringItems']();
}

export function ClearScriptError(arg1) {
  return window['go']['main']['App']['ClearScriptError'](arg1);
}

export function CreateOPCUAVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateOPCUAVariable'](arg1, arg2, arg3);
}

export function CreateScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateScript'](arg1, arg2, arg3);
}

export function CreateVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVariable'](arg1, arg2, arg3);
}

export function DeleteMonitoringItem(arg1) {
  return window['go']['main']['App']['DeleteMonitoringItem'](arg1);
}

export function DeleteOPCUAVariable(arg1) {
  return window['go']['main']['App']['DeleteOPCUAVariable'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function DeleteStructType(arg1) {
  return window['go']['main']['App']['DeleteStructType'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['App']['DeleteVariable'](arg1);
}

export function ExportProject() {
  return window['go']['main']['App']['ExportProject']();
}

export function GetAvailableProtocols() {
  return window['go']['main']['App']['GetAvailableProtocols']();
}

export function GetConsoleLogs() {
  return window['go']['main']['App']['GetConsoleLogs']();
}

export function GetDataTypes() {
  return window['go']['main']['App']['GetDataTypes']();
}

export function GetDisabledUnitIDs(arg1) {
  return window['go']['main']['App']['GetDisabledUnitIDs'](arg1);
}

export function GetIntervalPresets() {
  return window['go']['main']['App']['GetIntervalPresets']();
}

export function GetMemoryAreas(arg1) {
  return window['go']['main']['App']['GetMemoryAreas'](arg1);
}

export function GetMonitoringItems() {
  return window['go']['main']['App']['GetMonitoringItems']();
}

export function GetOPCUADataTypes() {
  return window['go']['main']['App']['GetOPCUADataTypes']();
}

export function GetOPCUAVariables() {
  return window['go']['main']['App']['GetOPCUAVariables']();
}

export function GetProtocolSchema(arg1) {
  return window['go']['main']['App']['GetProtocolSchema'](arg1);
}

export function GetScript(arg1) {
  return window['go']['main']['App']['GetScript'](arg1);
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function GetServerConfig(arg1) {
  return window['go']['main']['App']['GetServerConfig'](arg1);
}

export function GetServerInstances() {
  return window['go']['main']['App']['GetServerInstances']();
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetStructTypes() {
  return window['go']['main']['App']['GetStructTypes']();
}

export function GetUnitIDSettings(arg1) {
  return window['go']['main']['App']['GetUnitIDSettings'](arg1);
}

export function GetVariableMappings(arg1) {
  return window['go']['main']['App']['GetVariableMappings'](arg1);
}

export function GetVariables() {
  return window['go']['main']['App']['GetVariables']();
}

export function ImportProject() {
  return window['go']['main']['App']['ImportProject']();
}

export function IsOPCUAProtocol() {
  return window['go']['main']['App']['IsOPCUAProtocol']();
}

export function MoveMonitoringItem(arg1, arg2) {
  return window['go']['main']['App']['MoveMonitoringItem'](arg1, arg2);
}

export function ReadBits(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadBits'](arg1, arg2, arg3, arg4);
}

export function ReadWords(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadWords'](arg1, arg2, arg3, arg4);
}

export function RegisterStructType(arg1) {
  return window['go']['main']['App']['RegisterStructType'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}

export function ReorderMonitoringItem(arg1, arg2) {
  return window['go']['main']['App']['ReorderMonitoringItem'](arg1, arg2);
}

export function RunScriptOnce(arg1) {
  return window['go']['main']['App']['RunScriptOnce'](arg1);
}

export function SetDisabledUnitIDs(arg1, arg2) {
  return window['go']['main']['App']['SetDisabledUnitIDs'](arg1, arg2);
}

export function SetUnitIDEnabled(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetUnitIDEnabled'](arg1, arg2, arg3);
}

export function StartScript(arg1) {
  return window['go']['main']['App']['StartScript'](arg1);
}

export function StartServer(arg1) {
  return window['go']['main']['App']['StartServer'](arg1);
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function UpdateMonitoringItem(arg1) {
  return window['go']['main']['App']['UpdateMonitoringItem'](arg1);
}

export function UpdateOPCUAVariable(arg1, arg2) {
  return window['go']['main']['App']['UpdateOPCUAVariable'](arg1, arg2);
}

export function UpdateScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2, arg3, arg4);
}

export function UpdateServerConfig(arg1) {
  return window['go']['main']['App']['UpdateServerConfig'](arg1);
}

export function UpdateVariableMappings(arg1, arg2) {
  return window['go']['main']['App']['UpdateVariableMappings'](arg1, arg2);
}

export function UpdateVariableValue(arg1, arg2) {
  return window['go']['main']['App']['UpdateVariableValue'](arg1, arg2);
}

export function WriteBit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteBit'](arg1, arg2, arg3, arg4);
}

export function WriteWord(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteWord'](arg1, arg2, arg3, arg4);
}
